name: Open API descriptions update

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Checkout head branch
      run: |
        git fetch origin ${{ github.head_ref }}
        git switch ${{ github.head_ref }}
    - name: Update v1.0 OpenAPI description
      run: ./scripts/GenerateOpenApi.ps1 -endpointVersion "v1.0"
      shell: pwsh
    - name: Update beta OpenAPI description
      run: ./scripts/GenerateOpenApi.ps1 -endpointVersion "beta"
      shell: pwsh
    - name: Commit and push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add openapi/*
        git commit --allow-empty -m "Auto-updates OpenAPI descriptions"
        git push origin HEAD:${{ github.head_ref }}
