name: Open API descriptions update

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Checkout head branch
      run: |
        git fetch origin ${{ github.head_ref }}
        git switch ${{ github.head_ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - run: dotnet tool install -g Microsoft.OpenApi.Hidi --prerelease
      name: install hidi
    - name: Update v1.0 OpenAPI description
      run: ./scripts/GenerateOpenApi.ps1 -endpointVersion "v1.0" -Verbose
      shell: pwsh
    - name: Update beta OpenAPI description
      run: ./scripts/GenerateOpenApi.ps1 -endpointVersion "beta" -Verbose
      shell: pwsh
    - name: Commit and push
      run: |
        try {
          iex "git config user.name github-actions"
          iex "git config user.email github-actions@github.com"
          iex "git add openapi/*"
          iex "git commit -m 'Auto-updates OpenAPI descriptions'"
          iex "git push origin HEAD:${{ github.head_ref }}"
        }
        catch
        {
          Write-Warning "error with pushing updated OpenAPI descriptions $_"
          Write-Warning "This is most likely due to the fact that there are no changes to push."
        }
      shell: pwsh
